all: letters numbers firstname userinput newshell

letters: letters.c
	cc letters.c -o letters

numbers: numbers.c
	cc numbers.c -o numbers

firstname: firstname.c
	cc firstname.c -o firstname

userinput: userinput.c
	cc userinput.c -o userinput

newshell: newshell.c
	cc newshell.c -o newshell

clean:
	rm -f *.o
